### ISSUE TITLE
schema/mmif.json still has definitions for @context, view.@context, and mediumMetadata

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#102]
As of spec 0.2.1, there are still definitions for top-level `@context`, view-level `@context`, and `mediumMetadata`, though they are all optional (and mediumMetadata is totally orphaned).

**Comment by marcverhagen** [comment]
I left in the context because I would still like the option, should mention something about that in the specifications.

Will removing `mediumMetadata` impact the SDK? If not, I will put that change in spec-0.2.1.

Must think a little bit on whether we need metadata for our documents and how we deal with those if there is a need.

**Comment by keighrim** [comment]
Closed via #106 .
