### ISSUE TITLE
Annotation types

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#4]
This is a thread to discuss annotation types. 
<hr>
The goal of specifying annotation types is to form a vocabulary to use in MMIF annotation. Annotation types can be *hierarchically structured*, as we did in [lapps vocabulary](http://vocab.lappsgrid.org/). 

On the top-most, annotations will be anchored either one of: 

* time offsets (bars & tone, scene segmentation)
* character offsets (transcript, tokens, NE)
* bounding boxes (face recognition, OCR)

Let's call them time-based annotations (T-based), language-based (L-based), and image-based (I-based), respectively. And then there're annotations that link other annotations (or anchors) 
* relations, such as coreference: between L-based annotations
* forced alignment: L-based to T-based
* box alignment? (*need a good name*): timestamps of the bounding boxes

**Comment by keighrim** [comment]
The prototype of vocabulary and vocabulary builder is being developed in [`vocabulary`](https://github.com/clamsproject/mmif/tree/vocabulary) branch.

**Comment by marcverhagen** [comment]
Yes, this is a good thread for general discussion (maybe not for little things about individual annotation types, might overwhelm this thread).

With box alignment you mean time stamping? We may not want to think of that as an alignment issue but as a grounding issue. In a video a box needs to be ground using coordinates and a time point or segment.

**Comment by keighrim** [comment]
Yup, by box alignment, I meant the encoding of originating frame number (or its time stamp) in a box representation. What I missed in the above (2-yr old) comment is the alignment of boxes to language (e.g. from OCR).

**Comment by marcverhagen** [comment]
We now have TimeFrame with subclasses Segment and Chapter. We motivate Segment by saying it is more concrete and has a type. We suggest we could use something like Chapter if we want something with specialized attributes and without the type. One problem with Segment is that amongst image and video people it is widely understood to be what we call a BoundingBox. Maybe we could remove Segment and have a timeFrameType on TimeFrame, or rename Segment (but we cannot use something like VideoFrame since that is not understood to be an interval by video people).

**Comment by marcverhagen** [comment]
BoundingBox for us is really a polygon and not a rectangular border as it is usually understood to be.

**Comment by keighrim** [comment]
Now that we have multiple versions of vocab release, and we have a finite number of annotation types we are targeting for September milestone, this issue seems to be too general and the discussion here is outdated. Closing this issue.
