### ISSUE TITLE
re-implement views, media, annotations as dict keyed by ID

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#40]
For faster access to individual objects, implement those as dicts in python, while keeping the actual serialization still to be lists as described in the specification.

**Comment by angus-lherrou** [comment]
I've created a draft PR #60 with my implementation of the changes we have discussed here as well as in our meetings. My code abstracts this implementation away from the Mmif and View classes themselves so that we can easily make changes to how these lists are implemented while keeping the rest of the codebase stable. The PR also adds `__getitem__` to Mmif and View, which allows the user to do, for example, mmif['m1'], mmif['v1'], and mmif['v1:bb1'] to get a medium, view, or annotation from a mmif file.

**Comment by angus-lherrou** [comment]
Let's discuss here all the pros and cons of dicts vs lists as the underlying implementation.

**Comment by keighrim** [comment]
closed vai #60
