### ISSUE TITLE
`discriminator` in MMIF

### ISSUE THREAD

**Issue by keighrim** [clamsproject/mmif#6]
In lapps, tools can handle different type of data formats (LIF, gate, UIMA, ...), so we needed to have a `discriminator` at the very beginning of the I/O to indicate in which format is current input. 
I wonder if that's still the case for the MMIF and CLAMS. 
If the CLAMS needs to be 100% compatible with all the lapps tools (including those handle non-LIF inputs, for instance UIMA-XML), we can still encode a LIF (with XML encoded) as a whole inside the MMIF - of course it would be ugly though.
Any idea is welcome.

**Comment by keighrim** [comment]
I think at the moment, we decided not to use `discriminator` in MMIF and therefore wrapping native LIF json string inside MMIF as a whole is not an option any more. So next questions will be the way LIF string/objects are wrapped and represented in MMIF. Are we all agree on this?

**Comment by marcverhagen** [comment]
Yeah, let's think that discriminator stuff through a bit more. Maybe having the discriminator as used in the Data object to give an indication of what is in the payload is fine. It could then be used to discriminate between LIF and MMIF (and others if we want). And it "might" make it easier for LAPPS services to be applied inside CLAMS. That is a big "might" though because as we know there can be many pieces of text inside of a MMIF file that we want to run an NLP tool over.

Not sure whether I understand this:

> we can still encode a LIF (with XML encoded) as a whole inside the MMIF - of course it would be ugly though.

That would be ugly indeed but why would we want to do that? Isn't MMIF already set up to deal with LIF? Sure, there are some differences in that there is no `text` property but instead text as one or more of the media, and views are as usual except that they refer to a media element.

The bigger question is how we incorporate LAPPS tools. There is some prose on this [here](https://github.com/clamsproject/mmif/tree/specification/specifications/draft#compatibility-with-lapps-tools), but that indeed needs more thought.

**Comment by keighrim** [comment]
Yes, I agree that we decided to handle only LIF json strings - maybe after I left the first comment. So ignore that outdated part you quoted.  

---
LAPPS services that produce LIF as output should indicate that in their metadata, so we can rely on that for integration (although the metadata might not be very reliable - that's a different story). Actual integration needs a lot more thoughts and careful design, as well as consideration of other new approaches we take in designing MMIF, such as #8.

**Comment by keighrim** [comment]
So we don't have `discriminator` field at the top; that will limit our lapps integration in that only tools that output `LIF`-formatted json can be considered for integration. I'll leave this open for future reference, until we actually start lapps integration.

**Comment by marcverhagen** [comment]
Yeah, that is a worry. But we will indeed be better able to figure this out once the first LAPPS tools is being integrated.

**Comment by keighrim** [comment]
We will not *start lapps integration* in the future because there is no longer functional lapps. Closing this issue as "won't fix".
