### ISSUE TITLE
Restrictions on keys in medium metadata and annotation properties

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#61]
#60 (at 5a53b53) implements `Annotation.add_property` and `Medium.add_metadata` using `setattr` (the previous code, which appeared to hint at `__setitem__`, was not yet implemented). This necessarily requires that all properties in the `annotationProperties` and `mediumMetadata` JSON objects be valid Python identifiers, and not just valid strings as before.

If this is a requirement that we are okay with, we can proceed with the change I've implemented in that commit. If we'd prefer not to have that restriction, we can implement it differently (i.e. with a field in the `AnnotationProperties` and `MediumMetadata` classes containing a dictionary and some magic methods to wrap around that).

**Comment by keighrim** [comment]
I like the idea of using `setattr` and `isidentifier`. However since users (devs of individual tools) can shove pretty much anything in the metadata object (e.g. a metadata key can start with a numeral), so unless we have a robust way to perform round-way string conversions (e.g. `@` <-> `_`), I think we might need to keep it as a old plain dict.

**Comment by angus-lherrou** [comment]
I agree with you. I can implement that in #60 or in the branch I'll create for #62 tomorrow.

Do you think we should retain the `AnnotationProperties` and `MediumMetadata` classes in that case, or just use plain dicts?

**Comment by keighrim** [comment]
Having them as python classes is still good idea, I think, so that we can have control over *reserved* fields (some required, others optional).

**Comment by keighrim** [comment]
@angus-lherrou a4fc12202480e5fcf2975a4ec1f9dce1a23ae3cc attempts to solve some issues from having two-tiered attributes in a class, namely some named attributes at first-class, and a `dict` for free-for-all optional (second-class) attributes (particularly [here](https://github.com/clamsproject/mmif/pull/71/commits/a4fc12202480e5fcf2975a4ec1f9dce1a23ae3cc#diff-a0338f55c99a95a4f458177e5bb2b34bR86-R106) and [here](https://github.com/clamsproject/mmif/pull/71/commits/a4fc12202480e5fcf2975a4ec1f9dce1a23ae3cc#diff-079fd4699add09eb2f82cd46274309f9R37-R46) in the code). The very problem I wanted to solve is when all fields of a MMIF object are optional, we don't want to that object serialized as `{"XXX": {}}` or `{"XXX": null}`, but just want to ignore that. I though that might related to this issue as well, and if wanted make sure if you have written something similar or maybe a better solution to that

**Comment by angus-lherrou** [comment]
That makes a lot of sense. I hadn't thought about the optional fields issue, so that's great, and I had been thinking along the same lines as far as having required attributes as first-class attributes.

One potential issue with the way you're handling private fields is that arbitrary user-defined attribute names might have trailing underscores, and those would disappear on serialization. So we could tell users about that behavior and restrict possible attribute names, or we could use a different way (maybe a "private_attributes" dict in every such object).

**Comment by keighrim** [comment]
Maybe we can move that logic up to the superclass `MmifObject` so that any MMIF object can have optional custom attributes.

Your point on the *private* marker is very valid, I think. I added that only to handle [name conflict](https://github.com/clamsproject/mmif/pull/71/commits/a4fc12202480e5fcf2975a4ec1f9dce1a23ae3cc#diff-a0338f55c99a95a4f458177e5bb2b34bR49-R57) btw `text` field and setter function for`text.@value`, and I'll revert the marker code and find another way to resolve the conflict.

**Comment by keighrim** [comment]
a7338a219b0cf7f808b38fdb42c0ea6415c6e6b2 (in [this file](https://github.com/clamsproject/mmif/pull/71/commits/a7338a219b0cf7f808b38fdb42c0ea6415c6e6b2#diff-a0338f55c99a95a4f458177e5bb2b34bR83)) is generalizing the idea of two-tiered class attributes. I think we might want the named vs unnamed attribute groups in the `MmifObject` super class so that *any* subclass can use the same logic (maybe a flag for disabling unnamed group would be a plus for those subclasses - e.g. [`annotation`](https://github.com/clamsproject/mmif/blob/master/schema/mmif.json#L196) - don't want them)

**Comment by keighrim** [comment]
#82 implements naming constraints on keys in MMIF object (basically by not posing any constraints). As we're happy so far with the implementation, I think this issues can be closed now.
