### ISSUE TITLE
Annotation vocabulary shortnames and ID prefixes

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/mmif#64]
Define a formal scheme for deriving unique shortnames and ID prefixes for MMIF vocabulary that is extensible to future LAPPS integration and user-defined ontologies

**Comment by angus-lherrou** [comment]
My current WIP implementation proposes the following scheme:

- A valid annotation `@type` is either a URI, a namespaced shortname, or a shortname on its own.
- If the `@type` is a URI, it is always valid.
- If the `@type` is a namespaced shortname, it is valid as long as the namespace is defined in the `vocab` package (currently only MMIF namespace is defined, in future probably LAPPS as well, in far future possibly support for user-defined namespaces/vocabularies). I'm proposing a colon-delimited syntax for namespaced shortnames, e.g. `MMIF:Vocabulary` or `LAPPS:Segment`.
- If the `@type` is a bare shortname, it is valid as long as it exists in the MMIF vocabulary (i.e., assumed to be in the MMIF namespace).
- The least-specific valid name for a type is considered the canonical representation for that type in the `@type` field. For example, the canonical representation of a MMIF BoundingBox is `BoundingBox`, the canonical representation of a LAPPS Segment is `LAPPS:Segment`, and the canonical representation of the "ArbitraryAnnotation" type defined at https://example.com/vocabulary/ArbitraryAnnotation is `https://example.com/vocabulary/ArbitraryAnnotation`. However, all valid names are accepted when processing `@type` from a MMIF file, and I could potentially add optional flags to enforce a minimum level of specificity in a given MMIF object (i.e. requiring an explicit namespace for MMIF shortnames, or requiring full URIs for everything).

@marcverhagen @keighrim I would love to hear your feedback on this proposal.

**Comment by angus-lherrou** [comment]
Now that we have `@context` in views, the need for full URIs for custom vocabularies is reduced, I think. I don't fully understand how JSON-LD works so it would be helpful if y'all could consider the above proposal and think about how we could adjust it based on the presence of `@context`, in addition to any other comments or suggestions you have.

**Comment by marcverhagen** [comment]
I think we should put this on the agenda for our next meeting. This needs more than a few emails back and forth.

**Comment by marcverhagen** [comment]
@angus-lherrou  @keighrim 

Well, maybe it does not need more than a few emails. 

The context files in the view do change the story a bit. Each view has either the CLAMS or LAPPS file:

- https://mmif.clams.ai/0.1.0/context/vocab-clams.json
- https://mmif.clams.ai/0.1.0/context/vocab-lapps.json

These contexts make sure that in a CLAMS view something like TimeFrame will be expanded to http://mmif.clams.ai/0.1.0/vocab/TimeFrame (which is actually an error, I need to change "vocab" into "vocabulary").

So I think the story is a bit simpler than you had it

- If the `@type` is a URI it is valid.
- If it is not a URI it should/will be expanded into a URI given the context file

I don't think we have name-spaced names like `LAPPS:NamedEntity` so that would be an addition that does not seem to add anything since the context acts as the namespace. 

Future third-party annotations should either use URI or use a user-defined context file.

There is the issue of requiring names to be in the vocabulary. That would simply be a check whether the URI exists. You did mention that if the `@type` is a URI then it is valid, so valid does not imply

**Comment by angus-lherrou** [comment]
`ViewMetadata.new_contain` still relies on `ViewMetadata._find_match_hotfix`, which I wrote to fix a bug [here](https://github.com/clamsproject/mmif/issues/56#issuecomment-670771906).

I forget what exactly we finally decided on for how we are currently handling `@type` equality and shortnames, but this hotfix should either be formalized into not a hotfix or replaced with more correct behavior.

**Comment by keighrim** [comment]
Turned out that https://github.com/clamsproject/mmif-python/pull/170 solves most of the problems in this issue, except that it doesn't implement a uniformed way to assign pre-defined shorter string prefixes of vocab types to (automatically) generate annotations IDs. 

Currently we have [`View.new_annotation` method](https://github.com/clamsproject/mmif-python/blob/a13d98caebc794a4343e551071e7d8d6e05efb77/mmif/serialize/view.py#L62) to create a new annotation in a view. The method signature now is
```python 
  def new_annotation(self, aid: str, at_type: Union[str, ThingTypesBase], overwrite=False) -> 'Annotation':
```

So if we have a pre-defined ID prefixes somewhere in `vocabulary` package, the above method can be simplified to something like this
```python 
  def new_annotation(self, at_type: Union[str, ThingTypesBase], aid: Optional[str] = None, overwrite=False) -> 'Annotation':
    if aid is None:
      aid = self.get_next_id(at_type)
    ... # continue creating an annotation
  
  def get_next_id(at_type):
    prefix = at_type.idprefix
    return f'{prefix}_{self.get_next_number(prefix)}'
```
and I really like the idea. mostly because it will prevent annotation ID collision almost always. 

One downside I can think right now is that it will break existing apps because the parameter order of the `new_annotation` method has to be changed, so I would like to hear what others think.

**Comment by keighrim** [comment]
After some thoughts, I think the ID prefixes pre-defined in the SDK not be always a good idea, mostly because, then, we need to formularize the format of the annotation IDs, and that means more complicated specification than necessary. (in the above example, it'd be {prefix}_{number}) What i thought is something like this; 

``` python 
# mmif-python/vocabulary/base_types.py
class TypesBase(object):
    _prefixes = {} # class var to keep prefixes
    
    def __init__(self, type_uri: str):
        ... # set base_uri, shortname, etc.
        if self.shortname not in self.__class__._prefixes:
            self.__class__._prefixes[self.shortname] = self.__class__.create_prefix(self.shortname))

    def __init__(self, shortname: str):
        # infers a even shorter prefix (e.g. Token -> t , TimeFrame -> tf, etc.)

# then in mmif-python/serialize/view.py
class View(MmifObject):
    ...
    def __init__():
        self._id_counts = {}
        ... # continue initialization

    def new_annotation(self, at_type: Union[str, ThingTypesBase], aid: Optional[str] = None, overwrite=False) -> 'Annotation':
    if aid is None:
        aid = self.get_next_id(at_type)
        ... # continue creating an annotation
  
    def get_next_id(self, at_type):
        prefix = at_type.__class__.prefix[at_type.shortname]
        return f'{prefix}_{self.get_next_number(prefix)}' # always use this format
    
    def get_next_number(self, prefix):
        next_number = self._id_counts.get(prefix,0) + 1
        self._id_counts[prefix] = next_number
        return next_number
        
# then in mmif-python/serialize/annotation.py
class Annotation(MmifObject):
    ...
    def _deserialize(self, input_dict: dict) -> None:
        self.at_type = input_dict.pop('_type')
        self.at_type.set_prefix(input_dict['properties']['id'].rsplit('_', 1)[0]) 
        # the above line updates BaseTypes.prefixes when reading an existing MMIF
        # and ensures an app continues to use the same prefix for the same type in the new view
        # but this can be a problem, 
        # if the input MMIF has non-standard format for annotation IDs 
        # (e.g. instead of 't_1' for a Token, it uses 'token1')
        super()._deserialize(input_dict)
```

We can give up the last part of the implementation (`annotation.py` part in the snippet). The result will be; 

* No consistency of ID prefi throughout a single MMIF file. But I think that's fine. We don't have any mechanism to force that kind of consistency now anyway.
* No need to specify or force the format of the ID (such as `xxx_#`). 
* Still keeping the good things from the rest of the implementation. 

Still curious about how others think. Let me know.

**Comment by keighrim** [comment]
Started a PR based on the above proposal. PR includes a breaking change (signature of `View::new_annotation` is changed) , so I need everyone's input on this.

**Comment by keighrim** [comment]
closed via https://github.com/clamsproject/mmif-python/pull/174
